# -*- coding: utf-8 -*-
"""zmp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D2WVk0DzcG0wdwr48VjTIZjI94Zno_3e
"""

def zmp_prediction(xlh, ylh, xrh, yrh, xrf, yrf, xlf, ylf):
    b1 = ylf-(((ylf-yrh)/(xlf-xrh))*xlf)
    b2 = yrf-(((yrf-ylh)/(xrf-xlh))*xrf)

    k1 = (ylf-yrh)/(xlf-xrh)
    k2 = (ylf-yrh)/(xlf-xrh)

    xs = (b2-b1)/(k1-k2)
    ys = (k1*xs)+b1

    Lrh_rf = math.sqrt((pow(xrh-xrf,2))+pow(yrh-yrf,2))
    Ls_rf = math.sqrt((pow(xs-xrf,2))+pow(ys-yrf,2))
    Ls_rh = math.sqrt((pow(xs-xrh,2))+pow(ys-yrh,2))

    x1 = (Lrh_rf*xs + Ls_rf*xrh + Ls_rg*xrf)/(Lrh_rf + Ls_rf + Ls_rf)
    y1 = (Lrh_rf*ys + Ls_rf*yrh + Ls_rg*yrf)/(Lrh_rf + Ls_rf + Ls_rf)